site_name: dfTimewolf
site_url: https://dfTimewolf.com/
nav:
    - Home: index.md
    - Getting started: getting-started.md
    - User manual: user-manual.md
    - Developers' guide: developers-guide.md
    - Architecture: architecture.md
    - Metawolf: metawolf.md
    - Recipe caveats: recipe-caveat.md

markdown_extensions:
  - meta
  - attr_list
  - toc:
      permalink: True

theme:
  name: readthedocs
  logo: _static/logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.sections
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/log2timeline/dftimewolf
